apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab23
  labels:
    app: frontend-lab23
spec:
  selector:
    matchLabels:
      app: frontend-lab23
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab23
    spec:
      containers:
        - name: frontend-lab23
          image: j931018/front-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
