apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab40
  labels:
    app: frontend-lab40
spec:
  selector:
    matchLabels:
      app: frontend-lab40
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab40
    spec:
      containers:
        - name: frontend-lab40
          image: j931018/front-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
